---
- name: Install packages
  homebrew:
    name:
      - age
      - bat
      - git-delta
      - eza
      - nvim
      - gh
      - ripgrep
      - fzf
    state: present
- name: Install nvm and node
  import_tasks: ./nvm.yaml
