---
- name: Install nvm and node
  block:
    - name: Check if nvm is installed
      ansible.builtin.stat:
        path: "{{ data_home }}/nvm/nvm.sh"
      register: nvm_installed
    - name: Get installed nvm version
      ansible.builtin.shell: |
        set -o pipefail
        export NVM_DIR="{{ data_home }}/nvm"
        . "$NVM_DIR/nvm.sh"
        nvm --version
      args:
        executable: /bin/bash
      register: nvm_current_version
      changed_when: false
      when: nvm_installed.stat.exists
    - name: Set nvm installation flag
      ansible.builtin.set_fact:
        nvm_install: "{{ not nvm_installed.stat.exists or nvm_current_version.stdout is version(nvm_version, '<') }}"
    - name: Remove previous nvm installation
      ansible.builtin.file:
        path: "{{ data_home }}/nvm"
        state: absent
      when: nvm_install
    - name: Clone nvm repository
      ansible.builtin.git:
        repo: https://github.com/nvm-sh/nvm.git
        dest: "{{ data_home }}/nvm"
        version: "v{{ nvm_version }}"
        depth: 1
      when: nvm_install
    - name: Check if node is installed
      ansible.builtin.shell: |
        set -o pipefail
        export NVM_DIR="{{ data_home }}/nvm"
        . "$NVM_DIR/nvm.sh"
        nvm which {{ node_version }} 2>/dev/null
      args:
        executable: /bin/bash
      register: node_installed
      changed_when: false
      failed_when: false
    - name: Install node via nvm
      ansible.builtin.shell: |
        set -o pipefail
        export NVM_DIR="{{ data_home }}/nvm"
        . "$NVM_DIR/nvm.sh"
        nvm install {{ node_version }}
        nvm alias default {{ node_version }}
      args:
        executable: /bin/bash
      when: node_installed.rc != 0
      changed_when: true
