---
- name: Install age
  block:
    - name: Check if age is installed
      ansible.builtin.command: which age
      register: age_installed
      changed_when: false
      failed_when: false
    - name: Get installed age version
      ansible.builtin.shell: |
        set -o pipefail
        age --version | awk 'match($0, /[0-9]+\.[0-9]+\.[0-9]+/) { printf substr($0, RSTART, RLENGTH); exit }'
      args:
        executable: /bin/bash
      register: age_current_version
      changed_when: false
      when: age_installed.rc == 0
    - name: Set age installation flag
      ansible.builtin.set_fact:
        age_install: "{{ age_installed.rc != 0 or age_current_version.stdout is version(age_version, '<') }}"
    - name: Remove previous age data
      ansible.builtin.file:
        path: "{{ data_home }}/age"
        state: absent
      when: age_install
    - name: Create age directory
      ansible.builtin.file:
        path: "{{ data_home }}/age"
        state: directory
        mode: "0755"
      when: age_install
    - name: Install age via tarball
      ansible.builtin.unarchive:
        src: "https://github.com/FiloSottile/age/releases/download/v{{ age_version }}/age-v{{ age_version }}-linux-amd64.tar.gz"
        dest: "{{ data_home }}/age"
        remote_src: true
        extra_opts:
          - --strip-components=1
      when: age_install
    - name: Create symlink for age
      ansible.builtin.file:
        src: "{{ data_home }}/age/age"
        dest: "{{ binary_home }}/age"
        state: link
        force: true
      when: age_install
    - name: Create symlink for age-keygen
      ansible.builtin.file:
        src: "{{ data_home }}/age/age-keygen"
        dest: "{{ binary_home }}/age-keygen"
        state: link
        force: true
      when: age_install
