---
- name: Install Bun
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://bun.sh/install | bash
  args:
    executable: /bin/bash
    creates: "{{ data_home }}/bun/bin/bun"
  environment:
    BUN_INSTALL: "{{ data_home }}/bun"
