---
- name: Install fzf
  block:
    - name: Check if fzf is installed
      ansible.builtin.command: which fzf
      register: fzf_installed
      changed_when: false
      failed_when: false
    - name: Get installed fzf version
      ansible.builtin.shell: |
        set -o pipefail
        fzf --version | awk 'match($0, /[0-9]+\.[0-9]+\.[0-9]+/) { printf substr($0, RSTART, RLENGTH); exit }'
      args:
        executable: /bin/bash
      register: fzf_current_version
      changed_when: false
      when: fzf_installed.rc == 0
    - name: Set fzf installation flag
      ansible.builtin.set_fact:
        fzf_install: "{{ fzf_installed.rc != 0 or fzf_current_version.stdout is version(fzf_version, '<') }}"
    - name: Install fzf via tarball
      ansible.builtin.unarchive:
        src: "https://github.com/junegunn/fzf/releases/download/v{{ fzf_version }}/fzf-{{ fzf_version }}-linux_amd64.tar.gz"
        dest: "{{ binary_home }}"
        remote_src: true
      when: fzf_install
