---
- name: Install ripgrep
  block:
    - name: Check if rg is installed
      ansible.builtin.command: which rg
      register: rg_installed
      changed_when: false
      failed_when: false
    - name: Get installed rg version
      ansible.builtin.shell: |
        set -o pipefail
        rg --version | awk 'match($0, /[0-9]+\.[0-9]+\.[0-9]+/) { printf substr($0, RSTART, RLENGTH); exit }'
      args:
        executable: /bin/bash
      register: rg_current_version
      changed_when: false
      when: rg_installed.rc == 0
    - name: Set rg installation flag
      ansible.builtin.set_fact:
        rg_install: "{{ rg_installed.rc != 0 or rg_current_version.stdout is version(ripgrep_version, '<') }}"
    - name: Remove previous ripgrep data
      ansible.builtin.file:
        path: "{{ data_home }}/ripgrep"
        state: absent
      when: rg_install
    - name: Create ripgrep directory
      ansible.builtin.file:
        path: "{{ data_home }}/ripgrep"
        state: directory
        mode: "0755"
      when: rg_install
    - name: Install ripgrep via tarball
      ansible.builtin.unarchive:
        src: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ data_home }}/ripgrep"
        remote_src: true
        extra_opts:
          - --strip-components=1
      when: rg_install
    - name: Create symlink for ripgrep
      ansible.builtin.file:
        src: "{{ data_home }}/ripgrep/rg"
        dest: "{{ binary_home }}/rg"
        state: link
        force: true
      when: rg_install
