---
- name: Configure git
  block:
    - name: Get git version
      ansible.builtin.command: git version # noqa: command-instead-of-module
      register: git_version_output
      changed_when: false
    - name: Parse git version
      ansible.builtin.set_fact:
        git_version: "{{ git_version_output.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)') }}"
    - name: Create git config directory
      ansible.builtin.file:
        path: "{{ config_home }}/git"
        state: directory
        mode: "0755"
    - name: Deploy Git config from template
      ansible.builtin.template:
        src: "{{ dotfile_home }}/config/git/.gitconfig.j2"
        dest: "{{ config_home }}/git/config"
        mode: "0644"
    - name: Create symlink for gitignore
      ansible.builtin.file:
        src: "{{ dotfile_home }}/config/git/.gitignore"
        dest: "{{ config_home }}/git/ignore"
        state: link
        force: true
